[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "otp-manager-python"
version = "1.0.0"
description = "OTP Manager official Python / Async Python SDK for 2FA TOTP integration"
readme = "README.md"
authors = [{ name = "OTP Manager", email = "info@malatya.bel.tr" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "requests>=2.25.0",
]

[project.optional-dependencies]
async = [
    "httpx>=0.20.0",
]

[project.urls]
"Homepage" = "https://github.com/otp-manager/otp-manager-python"
